site_name: Programming, Artificial Intelligence and Robotics (II) - 3.º ESO
use_directory_urls: false

nav:
  - "Presentation": "contents/unit00/presentation.md"

  - "Programming, AI & Robots":
      - "Introduction to AI, Programming and Robotics": "contents/unit01/unit1.md"
      - "The Turing Test": "contents/unit01/c0_the-turing-test.md"
      - "Activity: Introduction to Artificial Intelligence: The Turing Test": "contents/unit01/c0_text-turing.md"
      - "▶ Neural Networks and Deep Learning": "contents/unit01/neural_deeplearn.md"
      - "▶ AlphaGo: NN & DL": "contents/unit01/alphago.md"
      - "Activity: Artificial Intelligence Techniques, Applications and Ethics": "contents/unit01/alphago_activity.md"
      - "Reading: The Impact of AI, Programming, and Robotics": "contents/unit01/reading_PAIR.md"
      - "Reading (Summary): The Impact of AI, Programming, and Robotics": "contents/unit01/reading_PAIR_A.md"

  # - "AI terms": "contents/unit01/terms.md"

  - "Programming Fundamentals":
      - "Compilation and Interpretation": "contents/unit02/compile_interpret.md"
      - "Programming Fundamentals: Data, Logic, and Control": "contents/unit02/unit2.md"

      - "Project: Coin Flip Simulator":
          - "Coin Flip: The project": "contents/unit02/flipcoin/flipcoin.md"
          - "Step 1: Flip coins and count the throws": "contents/unit02/flipcoin/vars_mainloop.md"
          - "Step 2: Animate and count heads and tails": "contents/unit02/flipcoin/checkflip.md"
          - "Step 3: Calculate percentages": "contents/unit02/flipcoin/calculations.md"
          - "Step 4: Display a simulation graph": "contents/unit02/flipcoin/graph.md"

  - "Modeling and Algorithms":
      - "Modeling, Algorithms, and Patterns in Programming": "contents/unit03/unit3.md"

      - "Programming with Python":
          - "Overview": "contents/programming/overview.md"
          - "Python Basics": "contents/programming/python_basic.md"
          - "Variables and data types": "contents/programming/variables.md"
          - "Code Example": "contents/programming/code_example.md"
          - "Exercises": "contents/programming/exercises.md"
          - "Presentation": "contents/programming/slides.md"

  # - "Exercises (Solutions)": "contents/programming/exercises_solution.md"

  - "Advanced Programming: Flow Control, Functions and Apps":
      - "Functions in Python: Basic Concepts": "contents/programming/functions.md"
      - "Creating an App: The Basics": "contents/programming/basics.md"
      - "Basic Code Challenges": "contents/programming/challenges_A.md"
      - "Code Challenge: The Average": "contents/programming/challenge_theaverage.md"

  # - "Unit 5. Software Management":
  #   - "Introduction": "contents/unit05/unit5.md"
  #   - "Introduction to Programming in High-Level Languages": "contents/unit05/proglang.md"
  #   - "Software Evaluation and Maintenance": "contents/unit05/sweval.md"
  #   - "Software Licenses. Free Software and Proprietary Software": "contents/unit05/swlicenses.md"
  #   - "Free Software Licenses": "contents/unit05/freeswlicenses.md"
  #   - "Creative Commons Licenses": "contents/unit05/creativecommons.md"

  - "Robotics":
      #- "Robotics in Action: Assembly, Control, and Programming": "contents/unit06/unit6.md"
      #- "Documentary: AI Tipping Point": "contents/unit06/ai_tippingpoint.md"

      - "Introduction to Robotics":
          #- "Introduction": "contents/unit06/intro.md"
          - "What is a robot?": "contents/unit06/robots.md"
          - "Robots and AI": "contents/unit06/robots_ai.md"
          - "Robots": "contents/unit06/crashcourse_robots.md"
          - "Robotics and AI": "contents/unit06/crashcourse_robotics_ai.md"
          - "How Engineering Robots Works": "contents/unit06/crashcourse_robots_engineering.md"

      # - "[2ESO] 1. Robots: Types, Degrees of Freedom, and Basic Technical Characteristics":
      #     - "Item": "contents/unit06/item.md"

      # - "1. Robot assembly":
      #     - "Item"

      #- "2. Control of robotic systems":

      - "Sensors, actuators and controllers":
          - "Introduction": "contents/unit06/intro_sens_act_contr.md"
          - "Sensors": "contents/unit06/sensors.md"
          - "Actuators": "contents/unit06/actuators.md"
          - "Controllers": "contents/unit06/controllers.md"
          - "mBot": "contents/unit06/mbot.md"
      - "Project: Programming a robot":
        - "mBlock" : "contents/unit06/mblock.md"
        - "mBot Robot Programming": "contents/unit06/mbotcode.md"

      #- "4. Loading and execution of algorithms in robots":
      #    - "Item"

theme:
  language: es
  name: "readthedocs"

  palette:
    primary: "Teal"
    accent: "Teal"

  font:
    text: Roboto
    code: Roboto Mono

  logo: "images/floppy-ict3.png"

plugins:
  - mkdocs-pdf
  - glightbox
  - search
  - mermaid2

  # - pandoc
  # pandoc:
  #   - combined: true

markdown_extensions:
  - attr_list
  - sane_lists

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - css/ict.css

extra_javascript:
  - javascript/extra.js
  - https://unpkg.com/mermaid@10.2.4/dist/mermaid.min.js